import path from "path"
import tailwindcss from "@tailwindcss/vite"
import react from "@vitejs/plugin-react"
import babel from "@rolldown/plugin-babel"
import { tanstackRouter } from "@tanstack/router-plugin/vite"
import { lingui, linguiTransformerBabelPreset } from "@lingui/vite-plugin"
import { defineConfig } from "vite"

// https://vite.dev/config/
export default defineConfig({
  // The panel lives under /admin, because "/" belongs to the site being
  // published — every hosted site serves its own pages there.
  base: "/admin/",
  build: {
    // Written but not advertised: the .js carries no sourceMappingURL, so a
    // browser never asks for the map. The image build uploads them to the
    // error tracker if one is configured, and deletes them either way.
    sourcemap: "hidden",
  },
  plugins: [
    tanstackRouter({ target: "react", autoCodeSplitting: true }),
    react(),
    tailwindcss(),
    lingui(),
    babel({ presets: [linguiTransformerBabelPreset()] }),
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
      // The canonical API contract generated by the Rust server.
      "@api": path.resolve(__dirname, "./src/api/server.ts"),
    },
  },
  server: {
    allowedHosts: [".trycloudflare.com"],
    proxy: {
      "/api": {
        target: process.env.VITE_API_PROXY_TARGET ?? "http://localhost:8080",
        changeOrigin: true,
      },
      "/public": {
        target: process.env.VITE_API_PROXY_TARGET ?? "http://localhost:8080",
        changeOrigin: true,
      },
      "/student": {
        target: process.env.VITE_API_PROXY_TARGET ?? "http://localhost:8080",
        changeOrigin: true,
      },
      "/mcp": {
        target: process.env.VITE_API_PROXY_TARGET ?? "http://localhost:8080",
        changeOrigin: true,
      },
      "/openapi.json": {
        target: process.env.VITE_API_PROXY_TARGET ?? "http://localhost:8080",
        changeOrigin: true,
      },
    },
  },
})
